CREATE TABLE users(
	"id" SERIAL PRIMARY KEY,
	"name" VARCHAR(50) NOT NULL,
	"email" TEXT UNIQUE NOT NULL,
	"cpf" VARCHAR(11) UNIQUE NOT NULL,
	"password" TEXT NOT NULL,
	CONSTRAINT "chk_cpf" CHECK (LENGTH ("cpf") = 11)
);